~/scratch/mpns_clang/build/bin/clang -c gen/globals_user.c -o gen/globals_user.o
~/scratch/mpns_clang/build/bin/clang -c user_lib/socket.c -o user_lib/socket.o
~/scratch/mpns_clang/build/bin/clang++ -o fobjs/nginx \
fobjs/src/core/nginx.o \
fobjs/src/core/ngx_log.o \
fobjs/src/core/ngx_palloc.o \
fobjs/src/core/ngx_array.o \
fobjs/src/core/ngx_list.o \
fobjs/src/core/ngx_hash.o \
fobjs/src/core/ngx_buf.o \
fobjs/src/core/ngx_queue.o \
fobjs/src/core/ngx_output_chain.o \
fobjs/src/core/ngx_string.o \
fobjs/src/core/ngx_parse.o \
fobjs/src/core/ngx_parse_time.o \
fobjs/src/core/ngx_inet.o \
fobjs/src/core/ngx_file.o \
fobjs/src/core/ngx_crc32.o \
fobjs/src/core/ngx_murmurhash.o \
fobjs/src/core/ngx_md5.o \
fobjs/src/core/ngx_sha1.o \
fobjs/src/core/ngx_rbtree.o \
fobjs/src/core/ngx_radix_tree.o \
fobjs/src/core/ngx_slab.o \
fobjs/src/core/ngx_times.o \
fobjs/src/core/ngx_shmtx.o \
fobjs/src/core/ngx_connection.o \
fobjs/src/core/ngx_cycle.o \
fobjs/src/core/ngx_spinlock.o \
fobjs/src/core/ngx_rwlock.o \
fobjs/src/core/ngx_cpuinfo.o \
fobjs/src/core/ngx_conf_file.o \
fobjs/src/core/ngx_module.o \
fobjs/src/core/ngx_resolver.o \
fobjs/src/core/ngx_open_file_cache.o \
fobjs/src/core/ngx_crypt.o \
fobjs/src/core/ngx_proxy_protocol.o \
fobjs/src/core/ngx_syslog.o \
fobjs/src/event/ngx_event.o \
fobjs/src/event/ngx_event_timer.o \
fobjs/src/event/ngx_event_posted.o \
fobjs/src/event/ngx_event_accept.o \
fobjs/src/event/ngx_event_udp.o \
fobjs/src/event/ngx_event_connect.o \
fobjs/src/event/ngx_event_pipe.o \
fobjs/src/os/unix/ngx_time.o \
fobjs/src/os/unix/ngx_errno.o \
fobjs/src/os/unix/ngx_alloc.o \
fobjs/src/os/unix/ngx_files.o \
fobjs/src/os/unix/ngx_socket.o \
fobjs/src/os/unix/ngx_recv.o \
fobjs/src/os/unix/ngx_readv_chain.o \
fobjs/src/os/unix/ngx_udp_recv.o \
fobjs/src/os/unix/ngx_send.o \
fobjs/src/os/unix/ngx_writev_chain.o \
fobjs/src/os/unix/ngx_udp_send.o \
fobjs/src/os/unix/ngx_udp_sendmsg_chain.o \
fobjs/src/os/unix/ngx_channel.o \
fobjs/src/os/unix/ngx_shmem.o \
fobjs/src/os/unix/ngx_process.o \
fobjs/src/os/unix/ngx_daemon.o \
fobjs/src/os/unix/ngx_setaffinity.o \
fobjs/src/os/unix/ngx_setproctitle.o \
fobjs/src/os/unix/ngx_posix_init.o \
fobjs/src/os/unix/ngx_user.o \
fobjs/src/os/unix/ngx_dlopen.o \
fobjs/src/os/unix/ngx_process_cycle.o \
fobjs/src/os/unix/ngx_linux_init.o \
fobjs/src/event/modules/ngx_epoll_module.o \
fobjs/src/os/unix/ngx_linux_sendfile_chain.o \
fobjs/src/core/ngx_regex.o \
fobjs/src/http/ngx_http.o \
fobjs/src/http/ngx_http_core_module.o \
fobjs/src/http/ngx_http_special_response.o \
fobjs/src/http/ngx_http_request.o \
fobjs/src/http/ngx_http_parse.o \
fobjs/src/http/modules/ngx_http_log_module.o \
fobjs/src/http/ngx_http_request_body.o \
fobjs/src/http/ngx_http_variables.o \
fobjs/src/http/ngx_http_script.o \
fobjs/src/http/ngx_http_upstream.o \
fobjs/src/http/ngx_http_upstream_round_robin.o \
fobjs/src/http/ngx_http_file_cache.o \
fobjs/src/http/ngx_http_write_filter_module.o \
fobjs/src/http/ngx_http_header_filter_module.o \
fobjs/src/http/modules/ngx_http_chunked_filter_module.o \
fobjs/src/http/modules/ngx_http_range_filter_module.o \
fobjs/src/http/modules/ngx_http_gzip_filter_module.o \
fobjs/src/http/ngx_http_postpone_filter_module.o \
fobjs/src/http/modules/ngx_http_ssi_filter_module.o \
fobjs/src/http/modules/ngx_http_charset_filter_module.o \
fobjs/src/http/modules/ngx_http_userid_filter_module.o \
fobjs/src/http/modules/ngx_http_headers_filter_module.o \
fobjs/src/http/ngx_http_copy_filter_module.o \
fobjs/src/http/modules/ngx_http_not_modified_filter_module.o \
fobjs/src/http/modules/ngx_http_static_module.o \
fobjs/src/http/modules/ngx_http_autoindex_module.o \
fobjs/src/http/modules/ngx_http_index_module.o \
fobjs/src/http/modules/ngx_http_mirror_module.o \
fobjs/src/http/modules/ngx_http_try_files_module.o \
fobjs/src/http/modules/ngx_http_auth_basic_module.o \
fobjs/src/http/modules/ngx_http_access_module.o \
fobjs/src/http/modules/ngx_http_limit_conn_module.o \
fobjs/src/http/modules/ngx_http_limit_req_module.o \
fobjs/src/http/modules/ngx_http_geo_module.o \
fobjs/src/http/modules/ngx_http_map_module.o \
fobjs/src/http/modules/ngx_http_split_clients_module.o \
fobjs/src/http/modules/ngx_http_referer_module.o \
fobjs/src/http/modules/ngx_http_rewrite_module.o \
fobjs/src/http/modules/ngx_http_proxy_module.o \
fobjs/src/http/modules/ngx_http_fastcgi_module.o \
fobjs/src/http/modules/ngx_http_uwsgi_module.o \
fobjs/src/http/modules/ngx_http_scgi_module.o \
fobjs/src/http/modules/ngx_http_memcached_module.o \
fobjs/src/http/modules/ngx_http_empty_gif_module.o \
fobjs/src/http/modules/ngx_http_browser_module.o \
fobjs/src/http/modules/ngx_http_upstream_hash_module.o \
fobjs/src/http/modules/ngx_http_upstream_ip_hash_module.o \
fobjs/src/http/modules/ngx_http_upstream_least_conn_module.o \
fobjs/src/http/modules/ngx_http_upstream_random_module.o \
fobjs/src/http/modules/ngx_http_upstream_keepalive_module.o \
fobjs/src/http/modules/ngx_http_upstream_zone_module.o \
fobjs/ngx_modules.o user_lib/ibv_network.o \
user_lib/socket.o gen/globals_user.o \
~/scratch/echo-bench/erpc-exp/ibv_test/basic/halloc.cc \
~/scratch/echo-bench/erpc-exp/ibv_test/basic/transport.cc \
-ldl -lpthread -lcrypt -lpcre -lz -libverbs
