gcc -o memcached_instrumented \
instrumented_compiled/assoc.o \
instrumented_compiled/authfile.o \
instrumented_compiled/bipbuffer.o \
instrumented_compiled/cache.o \
instrumented_compiled/crc32c.o \
instrumented_compiled/daemon.o \
instrumented_compiled/extstore.o \
instrumented_compiled/hash.o \
instrumented_compiled/items.o \
instrumented_compiled/itoa_ljust.o \
instrumented_compiled/jenkins_hash.o \
instrumented_compiled/logger.o \
instrumented_compiled/memcached.o \
instrumented_compiled/murmur3_hash.o \
instrumented_compiled/proto_bin.o \
instrumented_compiled/proto_text.o \
instrumented_compiled/restart.o \
instrumented_compiled/slab_automove_extstore.o \
instrumented_compiled/slab_automove.o \
instrumented_compiled/slabs.o \
instrumented_compiled/stats_prefix.o \
instrumented_compiled/storage.o \
instrumented_compiled/thread.o \
instrumented_compiled/util.o \
instrumented_compiled/crawler.o \
support/trace_support.c \
-lpthread -levent