srcs="core/nginx \
core/ngx_log \
core/ngx_palloc \
core/ngx_array \
core/ngx_list \
core/ngx_hash \
core/ngx_buf \
core/ngx_queue \
core/ngx_output_chain \
core/ngx_string \
core/ngx_parse \
core/ngx_parse_time \
core/ngx_inet \
core/ngx_file \
core/ngx_crc32 \
core/ngx_murmurhash \
core/ngx_md5 \
core/ngx_sha1 \
core/ngx_rbtree \
core/ngx_radix_tree \
core/ngx_slab \
core/ngx_times \
core/ngx_shmtx \
core/ngx_connection \
core/ngx_cycle \
core/ngx_spinlock \
core/ngx_rwlock \
core/ngx_cpuinfo \
core/ngx_conf_file \
core/ngx_module \
core/ngx_resolver \
core/ngx_open_file_cache \
core/ngx_crypt \
core/ngx_proxy_protocol \
core/ngx_syslog \
event/ngx_event \
event/ngx_event_timer \
event/ngx_event_posted \
event/ngx_event_accept \
event/ngx_event_udp \
event/ngx_event_connect \
event/ngx_event_pipe \
os/unix/ngx_time \
os/unix/ngx_errno \
os/unix/ngx_alloc \
os/unix/ngx_files \
os/unix/ngx_socket \
os/unix/ngx_recv \
os/unix/ngx_readv_chain \
os/unix/ngx_udp_recv \
os/unix/ngx_send \
os/unix/ngx_writev_chain \
os/unix/ngx_udp_send \
os/unix/ngx_udp_sendmsg_chain \
os/unix/ngx_channel \
os/unix/ngx_shmem \
os/unix/ngx_process \
os/unix/ngx_daemon \
os/unix/ngx_setaffinity \
os/unix/ngx_setproctitle \
os/unix/ngx_posix_init \
os/unix/ngx_user \
os/unix/ngx_dlopen \
os/unix/ngx_process_cycle \
os/unix/ngx_linux_init \
event/modules/ngx_epoll_module \
os/unix/ngx_linux_sendfile_chain \
core/ngx_regex \
http/ngx_http \
http/ngx_http_core_module \
http/ngx_http_special_response \
http/ngx_http_request \
http/ngx_http_parse \
http/modules/ngx_http_log_module \
http/ngx_http_request_body \
http/ngx_http_variables \
http/ngx_http_script \
http/ngx_http_upstream \
http/ngx_http_upstream_round_robin \
http/ngx_http_file_cache \
http/ngx_http_write_filter_module \
http/ngx_http_header_filter_module \
http/modules/ngx_http_chunked_filter_module \
http/modules/ngx_http_range_filter_module \
http/modules/ngx_http_gzip_filter_module \
http/ngx_http_postpone_filter_module \
http/modules/ngx_http_ssi_filter_module \
http/modules/ngx_http_charset_filter_module \
http/modules/ngx_http_userid_filter_module \
http/modules/ngx_http_headers_filter_module \
http/ngx_http_copy_filter_module \
http/modules/ngx_http_not_modified_filter_module \
http/modules/ngx_http_static_module \
http/modules/ngx_http_autoindex_module \
http/modules/ngx_http_index_module \
http/modules/ngx_http_mirror_module \
http/modules/ngx_http_try_files_module \
http/modules/ngx_http_auth_basic_module \
http/modules/ngx_http_access_module \
http/modules/ngx_http_limit_conn_module \
http/modules/ngx_http_limit_req_module \
http/modules/ngx_http_geo_module \
http/modules/ngx_http_map_module \
http/modules/ngx_http_split_clients_module \
http/modules/ngx_http_referer_module \
http/modules/ngx_http_rewrite_module \
http/modules/ngx_http_proxy_module \
http/modules/ngx_http_fastcgi_module \
http/modules/ngx_http_uwsgi_module \
http/modules/ngx_http_scgi_module \
http/modules/ngx_http_memcached_module \
http/modules/ngx_http_empty_gif_module \
http/modules/ngx_http_browser_module \
http/modules/ngx_http_upstream_hash_module \
http/modules/ngx_http_upstream_ip_hash_module \
http/modules/ngx_http_upstream_least_conn_module \
http/modules/ngx_http_upstream_random_module \
http/modules/ngx_http_upstream_keepalive_module \
http/modules/ngx_http_upstream_zone_module \
http/modules/ngx_http_upload_module"
